### ISSUE TITLE
Docker + Go 1.18 = /bin/sh: CompileDaemon: not found

### ISSUE THREAD

**Issue by hwebb** [githubnemo/CompileDaemon#73]
It seems that it stopped working since the update of Go 1.18, the error is `/bin/sh: CompileDaemon: not found`
It works when I get Go image 1.17.

Here is my Dockerfile:

> FROM golang:alpine
> 
> WORKDIR /app
> 
> COPY ./ /app
> 
> RUN go mod download
> 
> RUN go get github.com/githubnemo/CompileDaemon
> 
> ENTRY
> 
> POINT CompileDaemon --build="go build -o /app/.bin/api-admin ./cmd/admin" --command=./.bin/api-admin

Thanks

**Comment by demivi** [comment]
Hi,
This is because "go get" does not build and install packages anymore. Use `go install <package>@<version>` instead:
`RUN go install github.com/githubnemo/CompileDaemon@latest`

Look for "go get" here https://tip.golang.org/doc/go1.18 and read https://go.dev/doc/go-get-install-deprecation for more details.

**Comment by hwebb** [comment]
That worked! Sorry I didn't read that deprecation.
Thanks
